info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/locations/{city}/:
    get:
      operationId: locations_read
      parameters:
      - in: path
        name: city
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - locations
servers:
- url: ''
